name: Kan jeg skrive
favicon: null
layout_spectrum: 0.49783
typography_spectrum: 0.28375
title: Kan en ingeniør skrive en bok?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.25
  lightness: 0.20712549006566405
  saturation: 0
  rhythmicContrast: 0.5899045881815255
purpose: []
